"""Wave 3 quality-cutoff transcode tests (SPEC.md §W3 T19, invariant V10).

Uses a REAL 1-second FLAC generated by ffmpeg (skipped if ffmpeg absent).
"""

from __future__ import annotations

import hashlib
import os
import shutil
import subprocess

import pytest

from src.core import config
from src.services.transcode import apply_quality_cutoff, ffmpeg_available
from tests.conftest import _make_track

pytestmark = pytest.mark.skipif(
    not ffmpeg_available(), reason="ffmpeg not on PATH"
)


def _sha(path: str) -> str:
    return hashlib.sha256(open(path, "rb").read()).hexdigest()


def _make_real_flac(tmp_path) -> str:
    out = str(tmp_path / "song.flac")
    subprocess.run(
        [
            "ffmpeg", "-hide_banner", "-loglevel", "error",
            "-f", "lavfi", "-i", "sine=frequency=440:duration=1",
            "-c:a", "flac", "-y", out,
        ],
        check=True,
    )
    assert os.path.isfile(out)
    return out


@pytest.fixture()
def flac_track(session, tmp_path):
    flac = _make_real_flac(tmp_path)
    t = _make_track(
        session,
        "spotify:track:w3t19a",
        status="downloaded",
        title="Lossless Song",
        artist="Flac Artist",
        format="flac",
        file_path=flac,
        file_size_bytes=os.path.getsize(flac),
        file_sha256=_sha(flac),
        download_method="spotiflac_deezer",
    )
    return t, flac


def test_cutoff_mp320_transcodes_and_updates_track(session, tmp_path, flac_track, monkeypatch):
    monkeypatch.setattr(config, "QUALITY_CUTOFF", "mp3_320")
    monkeypatch.setattr(config, "KEEP_FLAC_MASTER", False)
    t, flac = flac_track

    new_path, new_fmt = apply_quality_cutoff(t.file_path, t, session)

    assert new_fmt == "mp3"
    assert new_path.endswith(".mp3") and os.path.isfile(new_path)
    session.refresh(t)
    assert t.format == "mp3"
    assert t.file_path == new_path
    assert t.file_sha256 == _sha(new_path)
    assert t.file_size_bytes == os.path.getsize(new_path)
    assert not os.path.exists(flac), "FLAC intermediate must be removed (V10)"


def test_keep_flac_master_preserves_source(session, tmp_path, flac_track, monkeypatch):
    monkeypatch.setattr(config, "QUALITY_CUTOFF", "mp3_320")
    monkeypatch.setattr(config, "KEEP_FLAC_MASTER", True)
    t, flac = flac_track

    new_path, new_fmt = apply_quality_cutoff(t.file_path, t, session)

    assert new_fmt == "mp3"
    assert os.path.isfile(flac), "KEEP_FLAC_MASTER must preserve the source"


def test_cutoff_flac_is_noop(session, tmp_path, flac_track, monkeypatch):
    monkeypatch.setattr(config, "QUALITY_CUTOFF", "flac")
    t, flac = flac_track

    new_path, new_fmt = apply_quality_cutoff(t.file_path, t, session)

    assert new_path == flac
    assert new_fmt is None
    assert os.path.isfile(flac)


def test_mp3_input_is_noop(session, tmp_path, monkeypatch):
    monkeypatch.setattr(config, "QUALITY_CUTOFF", "mp3_320")
    mp3 = str(tmp_path / "already.mp3")
    shutil.copyfile(_make_real_flac(tmp_path), mp3 + ".tmp")  # bytes irrelevant
    open(mp3, "wb").write(b"id3fake")
    t = _make_track(
        session, "spotify:track:w3t19b", status="downloaded",
        format="mp3", file_path=mp3, download_method="ytdlp_ytm",
    )

    new_path, new_fmt = apply_quality_cutoff(mp3, t, session)

    assert new_path == mp3 and new_fmt is None


def test_ffmpeg_failure_returns_original(session, tmp_path, flac_track, monkeypatch):
    """Transcode failure must never destroy the lossless source."""
    monkeypatch.setattr(config, "QUALITY_CUTOFF", "mp3_320")
    t, flac = flac_track

    def boom(*a, **kw):
        import subprocess as _sp
        return _sp.CompletedProcess(args=[], returncode=1, stdout=b"", stderr=b"fake ffmpeg error")
    import src.services.transcode as tr
    monkeypatch.setattr(tr.subprocess, "run", boom)

    new_path, new_fmt = apply_quality_cutoff(t.file_path, t, session)

    assert new_path == flac and new_fmt is None
    assert os.path.isfile(flac), "source must survive failed transcode"
