"""Add ON DELETE CASCADE to track_sources foreign keys.

The initial migration created track_sources FKs without CASCADE, so raw SQL
deletes on tracks/sources left orphaned rows. This migration drops and
re-creates both FKs with ON DELETE CASCADE.

Revision ID: 0002
Revises: 0001
Create Date: 2026-05-02
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op

revision: str = "0002"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop existing FKs (names generated by Alembic default naming convention)
    op.drop_constraint("track_sources_track_id_fkey",  "track_sources", type_="foreignkey")
    op.drop_constraint("track_sources_source_id_fkey", "track_sources", type_="foreignkey")

    # Re-create with ON DELETE CASCADE
    op.create_foreign_key(
        "track_sources_track_id_fkey",
        "track_sources", "tracks",
        ["track_id"], ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "track_sources_source_id_fkey",
        "track_sources", "sources",
        ["source_id"], ["id"],
        ondelete="CASCADE",
    )


def downgrade() -> None:
    op.drop_constraint("track_sources_track_id_fkey",  "track_sources", type_="foreignkey")
    op.drop_constraint("track_sources_source_id_fkey", "track_sources", type_="foreignkey")

    op.create_foreign_key(
        "track_sources_track_id_fkey",
        "track_sources", "tracks",
        ["track_id"], ["id"],
    )
    op.create_foreign_key(
        "track_sources_source_id_fkey",
        "track_sources", "sources",
        ["source_id"], ["id"],
    )
